apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: load-test
  namespace: k6-tests
spec:
  parallelism: 1
  script:
    configMap:
      name: k6-load-test
      file: load-test.js
  runner:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi
