# Multi-Cluster Service Export
# This demonstrates service discovery across member clusters

apiVersion: v1
kind: Namespace
metadata:
  name: multi-cluster-svc
  labels:
    app: multi-cluster-demo
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: multi-cluster-svc
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: multi-cluster-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mcr.microsoft.com/aks/samples/go-backend:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# ServiceExport makes this service available across the fleet
apiVersion: networking.fleet.azure.com/v1alpha1
kind: ServiceExport
metadata:
  name: backend-service
  namespace: multi-cluster-svc
