apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-secret-sync
  namespace: harbor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harbor-secret-sync
  template:
    metadata:
      labels:
        app: harbor-secret-sync
    spec:
      serviceAccountName: harbor
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: harbor-secrets
