apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: soak-test
  namespace: k6-tests
spec:
  parallelism: 1
  script:
    configMap:
      name: k6-soak-test
      file: soak-test.js
  runner:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
