apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: "https://aks-nginx-routing-kv.vault.azure.net/certificates/aks-ingress-tls/ffd803f3f1fd4962be0f4c85ad18a248" # Make sure to replace this with your KeyVault Certificate URI
  name: aks-helloworld-ssl
  namespace: app-routing-ssl-demo
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: ssl-demo.kasunrajapakse.xyz
    http:
      paths:
      - backend:
          service:
            name: aks-helloworld
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ssl-demo.kasunrajapakse.xyz
    secretName: keyvault-aks-helloworld-ssl # Make sure the ingress secret name start with keyvault-<secret name>