# Violates: allowed-repos (custom policy, K8sAllowedRepos) - image doesn't start with an allowed repo prefix
apiVersion: v1
kind: Pod
metadata:
  name: bad-disallowed-image
  namespace: workloads
  labels:
    team: platform
    environment: dev
spec:
  containers:
  - name: app
    image: docker.io/nginxinc/nginx-unprivileged:1.27-alpine
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: nginx-cache
      mountPath: /var/cache/nginx
    - name: nginx-run
      mountPath: /var/run
    - name: nginx-tmp
      mountPath: /tmp
  volumes:
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}
  - name: nginx-tmp
    emptyDir: {}
