apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-app
  namespace: keda-demo
  labels:
    app: cron-app
    scenario: cron
spec:
  replicas: 1    # KEDA will override this based on the cron schedule
  selector:
    matchLabels:
      app: cron-app
  template:
    metadata:
      labels:
        app: cron-app
        scenario: cron
    spec:
      containers:
        - name: cron-app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
