apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: smoke-test
  namespace: k6-tests
spec:
  parallelism: 1
  script:
    configMap:
      name: k6-smoke-test
      file: smoke-test.js
  runner:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
